### PR TITLE
Inline non-lodash stdlib functions, add all bitwise operators to stdlib

### PR DESCRIPTION
**Pull request by rattrayalex**
Addresses https://github.com/lightscript/babel-plugin-lightscript/issues/8
Also adds the rest of the binary operators. 

cc @wcjohnson

### CODE REVIEW

**Comment by wcjohnson** [comment]
Of the rare cases when people use bitwise operators at all, it's usually because they are looking for a performance gain. That would be lost if the bitwise operators get converted into a function call. Perhaps consider simply rewriting them in place: `CallExpression("bitwiseOr", a, b)` -> `BinOpExpression("|", a, b)`

**Comment by rattrayalex** [comment]
Interesting. I like the idea and hope to do it one day, but probably would want to think of it in the context of macros or function inlining generally.

For example, I've also been thinking about compiling `print(x)` to `console.log(x)`. I feel a bit wary about translating something that looks like a normal function call to something else, though. 

Do you think that sounds alright?

**Comment by wcjohnson** [comment]
Macros in general are an interesting feature, but I think this is a specific situation here that calls for a specific solution.

One of the LSC principles is that things should compile to the code you would have written. While it's rare to use bitwise operators at all, when someone does use them, they are basically never going to indirect them through a function call.

When we remove these operators from the language and make it so that the only way to access them is through a function call, we're making it impossible to write the kind of code that constitutes the most common use case for bitwise operations. I don't think that's a good idea. There should be some kind of escape valve to get to the code you want to write. I think the most straightforward escape valve is to just compile the English operators into the original ones.

I think given the fact that the replacement of the bitwise operator characters is presumably going to be a well documented part of the language, there won't be significant confusion surrounding the fact that  `bitwiseOr(a,b)` compiles to `a | b`

**Comment by rattrayalex** [comment]
I hear you. I'll probably do that in the future but it's not a priority now. I just don't​ have the time to implement / document it at the moment. 

In practice, the function overhead shouldn't be an issue in most cases, and when it is, it's likely to be inlined by V8. The escape hatch is to have the bitwise code written in a .js file. 

So I think the practical harm of punting on this until the language gets wider adoption is limited.

**Pull request merged**
